services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongo
  mongo:
    image: mongo
